"""Codegen tests — E2, E3.

Golden files live in tests/goldens/.
To regenerate: pytest --snapshot-update
"""
import json
from pathlib import Path

import pytest

from codegen.keyboard_h import generate_keyboard_h
from codegen.keyboard_c import generate_keyboard_c
from codegen.keymap_c import generate_keymap_c
from codegen.config_h import generate_config_h
from codegen.info_json import generate_info_json
from codegen.rules_mk import generate_rules_mk
from models import ColPin, KeyboardConfig, KeyDef, Layer, MatrixPin

GOLDENS = Path(__file__).parent / 'goldens'
UPDATE = False  # set via --snapshot-update flag in conftest


def _golden(name: str) -> Path:
    return GOLDENS / name


def _check_or_update(name: str, actual: str) -> None:
    path = _golden(name)
    if UPDATE or not path.exists():
        path.write_text(actual)
        return
    expected = path.read_text()
    assert actual == expected, f'Snapshot mismatch for {name}. Run pytest --snapshot-update to refresh.'


# ── A7 regression: LAYOUT defined in .h only ──────────────────────────────────

def test_layout_macro_in_info_json_not_header(minimal_avr_kb):
    h = generate_keyboard_h(minimal_avr_kb)
    c = generate_keyboard_c(minimal_avr_kb)
    assert '#define LAYOUT' not in h, 'LAYOUT macro must be generated by QMK from keyboard.json'
    assert '#define LAYOUT' not in c, 'LAYOUT macro must NOT be in keyboard.c'


def test_layout_no_impl_reference(minimal_avr_kb):
    h = generate_keyboard_h(minimal_avr_kb)
    assert 'LAYOUT_impl' not in h, 'LAYOUT_impl reference must not appear in header'


# ── A8 regression: undefined-matrix keys excluded ─────────────────────────────

def test_undefined_keys_excluded_from_layout(undefined_key_kb):
    info = json.loads(generate_info_json(undefined_key_kb))
    layout = info['layouts']['LAYOUT']['layout']
    labels = {key.get('label') for key in layout}
    assert 'undef' not in labels, 'Undefined key id must not appear in keyboard.json layout'


def test_undefined_keys_excluded_from_keymap(undefined_key_kb):
    c = generate_keymap_c(undefined_key_kb)
    assert 'undef' not in c, 'Undefined key id must not appear in keymap.c'


def test_layout_param_count_matches_defined_keys(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    layout = info['layouts']['LAYOUT']['layout']
    defined_keys = [k for k in minimal_avr_kb.keys if k.row is not None and k.col is not None]
    assert len(layout) == len(defined_keys)


def test_keyboard_h_uses_imported_layout_macro_name(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={'layout_macro': 'LAYOUT_ergodox'})

    info = json.loads(generate_info_json(kb))

    assert 'LAYOUT_ergodox' in info['layouts']
    assert 'LAYOUT' not in info['layouts']


def test_keymap_c_does_not_pad_layout_macro_arguments():
    kb = KeyboardConfig(
        id='odd',
        name='Odd Layout',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
            KeyDef(id='k2', x=2, y=0, row=0, col=2),
            KeyDef(id='k3', x=0, y=1, row=1, col=0),
        ],
        layers=[Layer(id='layer0', name='Base', keycodes={
            'k0': 'KC_A',
            'k1': 'KC_B',
            'k2': 'KC_C',
            'k3': 'KC_D',
        })],
    )

    c = generate_keymap_c(kb)

    assert 'KC_A, KC_B, KC_C,' in c
    assert 'KC_D' in c
    assert 'KC_D, KC_TRNS' not in c


def test_keymap_c_declares_imported_layer_and_custom_symbols():
    kb = KeyboardConfig(
        id='imported',
        name='Imported',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
            KeyDef(id='k2', x=2, y=0, row=0, col=2),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={
                'k0': 'LT(SYMB,KC_A)',
                'k1': 'LT(MDIA, KC_B)',
                'k2': 'VRSN',
            }),
            Layer(id='layer1', name='Symbols', keycodes={}),
            Layer(id='layer2', name='Media', keycodes={}),
        ],
    )

    c = generate_keymap_c(kb)

    assert 'enum nexus_layers {' in c
    assert 'SYMB = 1,' in c
    assert 'MDIA = 2,' in c
    assert '#define VRSN KC_NO' in c
    assert '#define KC_A KC_NO' not in c


def test_keymap_c_layer_symbol_enum_values_align_with_layer_indices():
    # _RAISE = 1 and _LOWER = 2 must match actual layer indices so MO() resolves correctly.
    kb = KeyboardConfig(
        id='aligned',
        name='Aligned',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={'k0': 'MO(_RAISE)', 'k1': 'MO(_LOWER)'}),
            Layer(id='layer1', name='Raise', keycodes={}),
            Layer(id='layer2', name='Lower', keycodes={}),
        ],
    )

    c = generate_keymap_c(kb)

    assert '_RAISE = 1,' in c
    assert '_LOWER = 2,' in c
    assert '[1] = LAYOUT' in c
    assert '[2] = LAYOUT' in c


def test_keymap_c_declares_missing_layer_symbols_referenced_by_base_layer():
    kb = KeyboardConfig(
        id='missing-layers',
        name='Missing Layers',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={
                'k0': 'MO(_RAISE)',
                'k1': 'MO(_LOWER)',
            }),
        ],
    )

    c = generate_keymap_c(kb)

    assert '_RAISE = 1,' in c
    assert '_LOWER = 2,' in c


def test_single_key_without_matrix_edges_generates_one_key_layout():
    kb = KeyboardConfig(
        id='single',
        name='Single',
        mcu='atmega32u4',
        keys=[KeyDef(id='only', x=0, y=0)],
        row_pins=[MatrixPin(row=0, pin='B0')],
        col_pins=[ColPin(col=0, pin='D0')],
        layers=[Layer(id='layer0', name='Base', keycodes={'only': 'KC_A'})],
    )

    h = generate_keyboard_h(kb)
    c = generate_keymap_c(kb)
    info = json.loads(generate_info_json(kb))

    assert '#define LAYOUT' not in h
    assert info['layouts']['LAYOUT']['layout'][0]['matrix'] == [0, 0]
    assert 'KC_A' in c


def test_mk20dx256_generates_arm_rules_and_kiibohd_bootloader(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={'mcu': 'mk20dx256'})

    rules = generate_rules_mk(kb)
    config = generate_config_h(kb)

    assert 'MCU = MK20DX256' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'F_CPU' not in rules
    assert '#define BOOTLOADER kiibohd' in config


# ── Snapshot tests ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize('fixture,gen_fn,suffix', [
    ('minimal_avr_kb', generate_keyboard_h, 'minimal_avr.keyboard_h'),
    ('minimal_avr_kb', generate_keyboard_c, 'minimal_avr.keyboard_c'),
    ('minimal_avr_kb', generate_keymap_c, 'minimal_avr.keymap_c'),
    ('minimal_avr_kb', generate_config_h, 'minimal_avr.config_h'),
    ('minimal_avr_kb', generate_rules_mk, 'minimal_avr.rules_mk'),
    ('split_rgb_kb', generate_keyboard_h, 'split_rgb.keyboard_h'),
    ('split_rgb_kb', generate_keyboard_c, 'split_rgb.keyboard_c'),
    ('split_rgb_kb', generate_keymap_c, 'split_rgb.keymap_c'),
    ('split_rgb_kb', generate_config_h, 'split_rgb.config_h'),
    ('split_rgb_kb', generate_rules_mk, 'split_rgb.rules_mk'),
    ('rp2040_oled_kb', generate_keyboard_h, 'rp2040_oled.keyboard_h'),
    ('rp2040_oled_kb', generate_keyboard_c, 'rp2040_oled.keyboard_c'),
    ('rp2040_oled_kb', generate_keymap_c, 'rp2040_oled.keymap_c'),
    ('rp2040_oled_kb', generate_config_h, 'rp2040_oled.config_h'),
    ('rp2040_oled_kb', generate_rules_mk, 'rp2040_oled.rules_mk'),
])
def test_snapshot(request, fixture, gen_fn, suffix):
    kb: KeyboardConfig = request.getfixturevalue(fixture)
    output = gen_fn(kb)
    _check_or_update(suffix, output)


# ── info_json field tests ──────────────────────────────────────────────────────

def test_info_json_minimal_avr_required_fields(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    assert info['debounce'] == 5, 'debounce must default to 5'
    assert 'url' in info, 'url field must be present'
    assert 'maintainer' in info, 'maintainer field must be present'
    assert 'bootloader' in info, 'bootloader field must be present'
    assert 'processor' in info, 'processor field must be present'
    assert info['processor'] == 'atmega32u4'
    assert info['bootloader'] == 'atmel-dfu'


def test_info_json_split_block_emitted_when_split_enabled(split_rgb_kb):
    info = json.loads(generate_info_json(split_rgb_kb))
    assert 'split' in info, 'split block must appear when split_keyboard feature is on'
    assert info['split']['enabled'] is True
    assert 'soft_serial_pin' in info['split']


def test_info_json_no_split_block_when_not_split(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    assert 'split' not in info, 'split block must not appear for non-split keyboard'


def test_info_json_rgb_matrix_block_emitted_when_enabled(split_rgb_kb):
    info = json.loads(generate_info_json(split_rgb_kb))
    assert 'rgb_matrix' in info, 'rgb_matrix block must appear when rgb_matrix feature is on'
    rgb = info['rgb_matrix']
    assert 'driver' in rgb
    assert 'led_count' in rgb
    assert rgb['led_count'] > 0
    # split_rgb_kb has all 4 keys with led_index set
    assert 'layout' in rgb
    assert len(rgb['layout']) == 4
    for entry in rgb['layout']:
        assert 'matrix' in entry
        assert 'x' in entry
        assert 'y' in entry
        assert entry['flags'] == 4


def test_info_json_rp2040_bootloader(rp2040_oled_kb):
    info = json.loads(generate_info_json(rp2040_oled_kb))
    assert info['bootloader'] == 'rp2040'
    assert info['processor'] == 'RP2040'
