"""Codegen tests — E2, E3.

Golden files live in tests/goldens/.
To regenerate: pytest --snapshot-update
"""
import json
from pathlib import Path

import pytest

from codegen.keyboard_h import generate_keyboard_h
from codegen.keyboard_c import generate_keyboard_c
from codegen.keymap_c import generate_keymap_c
from codegen.config_h import generate_config_h
from codegen.info_json import generate_info_json
from codegen.rules_mk import generate_rules_mk
from models import ColPin, KeyboardConfig, KeyDef, Layer, MatrixPin

GOLDENS = Path(__file__).parent / 'goldens'
UPDATE = False  # set via --snapshot-update flag in conftest


def _golden(name: str) -> Path:
    return GOLDENS / name


def _check_or_update(name: str, actual: str) -> None:
    path = _golden(name)
    if UPDATE or not path.exists():
        path.write_text(actual)
        return
    expected = path.read_text()
    assert actual == expected, f'Snapshot mismatch for {name}. Run pytest --snapshot-update to refresh.'


# ── A7 regression: LAYOUT defined in .h only ──────────────────────────────────

def test_layout_macro_in_info_json_not_header(minimal_avr_kb):
    h = generate_keyboard_h(minimal_avr_kb)
    c = generate_keyboard_c(minimal_avr_kb)
    assert '#define LAYOUT' not in h, 'LAYOUT macro must be generated by QMK from keyboard.json'
    assert '#define LAYOUT' not in c, 'LAYOUT macro must NOT be in keyboard.c'


def test_layout_no_impl_reference(minimal_avr_kb):
    h = generate_keyboard_h(minimal_avr_kb)
    assert 'LAYOUT_impl' not in h, 'LAYOUT_impl reference must not appear in header'


# ── A8 regression: undefined-matrix keys excluded ─────────────────────────────

def test_undefined_keys_excluded_from_layout(undefined_key_kb):
    info = json.loads(generate_info_json(undefined_key_kb))
    layout = info['layouts']['LAYOUT']['layout']
    labels = {key.get('label') for key in layout}
    assert 'undef' not in labels, 'Undefined key id must not appear in keyboard.json layout'


def test_undefined_keys_excluded_from_keymap(undefined_key_kb):
    c = generate_keymap_c(undefined_key_kb)
    assert 'undef' not in c, 'Undefined key id must not appear in keymap.c'


def test_layout_param_count_matches_defined_keys(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    layout = info['layouts']['LAYOUT']['layout']
    defined_keys = [k for k in minimal_avr_kb.keys if k.row is not None and k.col is not None]
    assert len(layout) == len(defined_keys)


def test_keyboard_h_uses_imported_layout_macro_name(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={'layout_macro': 'LAYOUT_ergodox'})

    info = json.loads(generate_info_json(kb))

    assert 'LAYOUT_ergodox' in info['layouts']
    assert 'LAYOUT' not in info['layouts']


def test_keymap_c_does_not_pad_layout_macro_arguments():
    kb = KeyboardConfig(
        id='odd',
        name='Odd Layout',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
            KeyDef(id='k2', x=2, y=0, row=0, col=2),
            KeyDef(id='k3', x=0, y=1, row=1, col=0),
        ],
        layers=[Layer(id='layer0', name='Base', keycodes={
            'k0': 'KC_A',
            'k1': 'KC_B',
            'k2': 'KC_C',
            'k3': 'KC_D',
        })],
    )

    c = generate_keymap_c(kb)

    assert 'KC_A, KC_B, KC_C,' in c
    assert 'KC_D' in c
    assert 'KC_D, KC_TRNS' not in c


def test_keymap_c_declares_imported_layer_and_custom_symbols():
    kb = KeyboardConfig(
        id='imported',
        name='Imported',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
            KeyDef(id='k2', x=2, y=0, row=0, col=2),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={
                'k0': 'LT(SYMB,KC_A)',
                'k1': 'LT(MDIA, KC_B)',
                'k2': 'VRSN',
            }),
            Layer(id='layer1', name='Symbols', keycodes={}),
            Layer(id='layer2', name='Media', keycodes={}),
        ],
    )

    c = generate_keymap_c(kb)

    assert 'enum nexus_layers {' in c
    assert 'SYMB = 1,' in c
    assert 'MDIA = 2,' in c
    assert '#define VRSN KC_NO' in c
    assert '#define KC_A KC_NO' not in c


def test_keymap_c_layer_symbol_enum_values_align_with_layer_indices():
    # _RAISE = 1 and _LOWER = 2 must match actual layer indices so MO() resolves correctly.
    kb = KeyboardConfig(
        id='aligned',
        name='Aligned',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={'k0': 'MO(_RAISE)', 'k1': 'MO(_LOWER)'}),
            Layer(id='layer1', name='Raise', keycodes={}),
            Layer(id='layer2', name='Lower', keycodes={}),
        ],
    )

    c = generate_keymap_c(kb)

    assert '_RAISE = 1,' in c
    assert '_LOWER = 2,' in c
    assert '[1] = LAYOUT' in c
    assert '[2] = LAYOUT' in c


def test_keymap_c_declares_missing_layer_symbols_referenced_by_base_layer():
    kb = KeyboardConfig(
        id='missing-layers',
        name='Missing Layers',
        mcu='atmega32u4',
        keys=[
            KeyDef(id='k0', x=0, y=0, row=0, col=0),
            KeyDef(id='k1', x=1, y=0, row=0, col=1),
        ],
        layers=[
            Layer(id='layer0', name='Base', keycodes={
                'k0': 'MO(_RAISE)',
                'k1': 'MO(_LOWER)',
            }),
        ],
    )

    c = generate_keymap_c(kb)

    assert '_RAISE = 1,' in c
    assert '_LOWER = 2,' in c


def test_single_key_without_matrix_edges_generates_one_key_layout():
    kb = KeyboardConfig(
        id='single',
        name='Single',
        mcu='atmega32u4',
        keys=[KeyDef(id='only', x=0, y=0)],
        row_pins=[MatrixPin(row=0, pin='B0')],
        col_pins=[ColPin(col=0, pin='D0')],
        layers=[Layer(id='layer0', name='Base', keycodes={'only': 'KC_A'})],
    )

    h = generate_keyboard_h(kb)
    c = generate_keymap_c(kb)
    info = json.loads(generate_info_json(kb))

    assert '#define LAYOUT' not in h
    assert info['layouts']['LAYOUT']['layout'][0]['matrix'] == [0, 0]
    assert 'KC_A' in c


def test_direct_matrix_generates_direct_pins_not_row_col_defines(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'direct_pins': [['C6', 'D6'], ['C7', None]],
        'row_pins': [MatrixPin(row=0, pin='C6'), MatrixPin(row=1, pin='C7')],
        'col_pins': [ColPin(col=0, pin='D6')],
    })

    info = json.loads(generate_info_json(kb))
    config = generate_config_h(kb)

    assert info['matrix_pins'] == {'direct': [['C6', 'D6'], ['C7', None]]}
    assert '#define MATRIX_ROW_PINS' not in config
    assert '#define MATRIX_COL_PINS' not in config


def test_mk20dx256_generates_arm_rules_and_kiibohd_bootloader(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={'mcu': 'mk20dx256'})

    rules = generate_rules_mk(kb)
    config = generate_config_h(kb)

    assert 'MCU = MK20DX256' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'F_CPU' not in rules
    assert '#define BOOTLOADER kiibohd' in config


def test_stm32f411_generates_arm_rules_and_stm32_dfu_metadata(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={'mcu': 'stm32f411'})

    rules = generate_rules_mk(kb)
    config = generate_config_h(kb)
    info = json.loads(generate_info_json(kb))

    assert 'MCU = STM32F411' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'F_CPU' not in rules
    assert '#define BOOTLOADER stm32-dfu' in config
    assert info['processor'] == 'STM32F411'
    assert info['bootloader'] == 'stm32-dfu'


@pytest.mark.parametrize('mcu,qmk_name,f_cpu,bootloader', [
    ('atmega32u2', 'atmega32u2', '16000000', 'atmel-dfu'),
    ('atmega32a', 'atmega32a', '12000000', 'bootloadhid'),
    ('at90usb1286', 'at90usb1286', '16000000', 'atmel-dfu'),
    ('atmega328p', 'atmega328p', '16000000', 'usbasploader'),
])
def test_requested_avr_mcus_generate_supported_rules_and_metadata(minimal_avr_kb, mcu, qmk_name, f_cpu, bootloader):
    kb = minimal_avr_kb.model_copy(update={'mcu': mcu})

    rules = generate_rules_mk(kb)
    config = generate_config_h(kb)
    info = json.loads(generate_info_json(kb))

    assert f'MCU = {qmk_name}' in rules
    assert f'F_CPU = {f_cpu}' in rules
    assert 'TARGET_ARCH = ARM' not in rules
    assert f'#define BOOTLOADER {bootloader}' in config
    assert info['processor'] == qmk_name
    assert info['bootloader'] == bootloader


def test_mk20dx256_generates_mcuconf_h(minimal_avr_kb):
    """IC_TEENSY_3_1 board has no configs/mcuconf.h; keyboard must supply its own."""
    from codegen.generator import generate_sources
    kb = minimal_avr_kb.model_copy(update={'mcu': 'mk20dx256'})

    sources = generate_sources(kb)

    assert 'mcuconf.h' in sources, 'mcuconf.h must be generated for mk20dx256'
    assert 'K20x_MCUCONF' in sources['mcuconf.h']
    assert 'KINETIS_USB_USE_USB0' in sources['mcuconf.h']


# ── Snapshot tests ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize('fixture,gen_fn,suffix', [
    ('minimal_avr_kb', generate_keyboard_h, 'minimal_avr.keyboard_h'),
    ('minimal_avr_kb', generate_keyboard_c, 'minimal_avr.keyboard_c'),
    ('minimal_avr_kb', generate_keymap_c, 'minimal_avr.keymap_c'),
    ('minimal_avr_kb', generate_config_h, 'minimal_avr.config_h'),
    ('minimal_avr_kb', generate_rules_mk, 'minimal_avr.rules_mk'),
    ('split_rgb_kb', generate_keyboard_h, 'split_rgb.keyboard_h'),
    ('split_rgb_kb', generate_keyboard_c, 'split_rgb.keyboard_c'),
    ('split_rgb_kb', generate_keymap_c, 'split_rgb.keymap_c'),
    ('split_rgb_kb', generate_config_h, 'split_rgb.config_h'),
    ('split_rgb_kb', generate_rules_mk, 'split_rgb.rules_mk'),
    ('rp2040_oled_kb', generate_keyboard_h, 'rp2040_oled.keyboard_h'),
    ('rp2040_oled_kb', generate_keyboard_c, 'rp2040_oled.keyboard_c'),
    ('rp2040_oled_kb', generate_keymap_c, 'rp2040_oled.keymap_c'),
    ('rp2040_oled_kb', generate_config_h, 'rp2040_oled.config_h'),
    ('rp2040_oled_kb', generate_rules_mk, 'rp2040_oled.rules_mk'),
])
def test_snapshot(request, fixture, gen_fn, suffix):
    kb: KeyboardConfig = request.getfixturevalue(fixture)
    output = gen_fn(kb)
    _check_or_update(suffix, output)


# ── info_json field tests ──────────────────────────────────────────────────────

def test_info_json_minimal_avr_required_fields(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    assert info['debounce'] == 5, 'debounce must default to 5'
    assert 'url' in info, 'url field must be present'
    assert 'maintainer' in info, 'maintainer field must be present'
    assert 'bootloader' in info, 'bootloader field must be present'
    assert 'processor' in info, 'processor field must be present'
    assert info['processor'] == 'atmega32u4'
    assert info['bootloader'] == 'atmel-dfu'


def test_info_json_split_block_emitted_when_split_enabled(split_rgb_kb):
    info = json.loads(generate_info_json(split_rgb_kb))
    assert 'split' in info, 'split block must appear when split_keyboard feature is on'
    assert info['split']['enabled'] is True
    assert 'soft_serial_pin' in info['split']


def test_info_json_no_split_block_when_not_split(minimal_avr_kb):
    info = json.loads(generate_info_json(minimal_avr_kb))
    assert 'split' not in info, 'split block must not appear for non-split keyboard'


def test_info_json_rgb_matrix_block_emitted_when_enabled(split_rgb_kb):
    info = json.loads(generate_info_json(split_rgb_kb))
    assert 'rgb_matrix' in info, 'rgb_matrix block must appear when rgb_matrix feature is on'
    rgb = info['rgb_matrix']
    assert 'driver' in rgb
    assert 'led_count' in rgb
    assert rgb['led_count'] > 0
    # split_rgb_kb has all 4 keys with led_index set
    assert 'layout' in rgb
    assert len(rgb['layout']) == 4
    for entry in rgb['layout']:
        assert 'matrix' in entry
        assert 'x' in entry
        assert 'y' in entry
        assert isinstance(entry['x'], int), 'rgb_matrix.layout x must be integer (QMK schema)'
        assert isinstance(entry['y'], int), 'rgb_matrix.layout y must be integer (QMK schema)'
        assert 0 <= entry['x'] <= 224
        assert 0 <= entry['y'] <= 64
        assert entry['flags'] == 4


def test_info_json_rp2040_bootloader(rp2040_oled_kb):
    info = json.loads(generate_info_json(rp2040_oled_kb))
    assert info['bootloader'] == 'rp2040'
    assert info['processor'] == 'RP2040'


def test_is31fl3731_split_generates_driver_count_and_addresses(split_rgb_kb):
    kb = split_rgb_kb.model_copy(update={
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    config = generate_config_h(kb)
    assert '#define IS31FL3731_DRIVER_COUNT 2' in config
    assert '#define IS31FL3731_I2C_ADDRESS_1 IS31FL3731_I2C_ADDRESS_GND' in config
    assert '#define IS31FL3731_I2C_ADDRESS_2 IS31FL3731_I2C_ADDRESS_GND' in config


def test_is31fl3731_non_split_generates_single_driver(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'features': {**minimal_avr_kb.features, 'rgb_matrix': True},
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    config = generate_config_h(kb)
    assert '#define IS31FL3731_DRIVER_COUNT 1' in config
    assert '#define IS31FL3731_I2C_ADDRESS_1 IS31FL3731_I2C_ADDRESS_GND' in config
    assert 'IS31FL3731_I2C_ADDRESS_2' not in config


def test_is31fl3731_keyboard_c_generates_driver_led_table(split_rgb_kb):
    kb = split_rgb_kb.model_copy(update={
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    keyboard_c = generate_keyboard_c(kb)

    assert '#include "drivers/led/issi/is31fl3731.h"' in keyboard_c
    assert 'const is31fl3731_led_t PROGMEM g_is31fl3731_leds[IS31FL3731_LED_COUNT]' in keyboard_c
    assert '{ 0, C1_1, C2_1, C3_1 },' in keyboard_c
    assert '{ 1, C1_1, C2_1, C3_1 },' in keyboard_c


def test_is31fl3731_on_mk20dx256_adds_i2c_pal_mode_overrides(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'mcu': 'mk20dx256',
        'features': {**minimal_avr_kb.features, 'rgb_matrix': True},
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    config = generate_config_h(kb)
    assert '#define I2C1_SCL_PAL_MODE PAL_MODE_OUTPUT_OPENDRAIN' in config
    assert '#define I2C1_SDA_PAL_MODE PAL_MODE_OUTPUT_OPENDRAIN' in config


def test_is31fl3731_on_non_kinetis_no_pal_mode_overrides(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'mcu': 'stm32f303',
        'features': {**minimal_avr_kb.features, 'rgb_matrix': True},
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    config = generate_config_h(kb)
    assert 'I2C1_SCL_PAL_MODE' not in config
    assert 'I2C1_SDA_PAL_MODE' not in config


def test_mk20dx256_split_emits_usart_serial_driver(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'mcu': 'mk20dx256',
        'features': {**minimal_avr_kb.features, 'split_keyboard': True},
        'soft_serial_pin': 'D2',
    })
    rules = generate_rules_mk(kb)
    assert 'SPLIT_TRANSPORT = serial' in rules
    assert 'SERIAL_DRIVER = usart' in rules


def test_rp2040_split_uses_gpio_pin_fallback_and_imported_serial_driver(rp2040_oled_kb):
    kb = rp2040_oled_kb.model_copy(update={
        'features': {**rp2040_oled_kb.features, 'split_keyboard': True},
        'soft_serial_pin': 'D0',
        'feature_configs': {
            'split_keyboard': {
                'SPLIT_TRANSPORT': 'serial',
                'SERIAL_DRIVER': 'vendor',
            },
        },
    })

    config = generate_config_h(kb)
    rules = generate_rules_mk(kb)

    assert '#define SOFT_SERIAL_PIN GP0' in config
    assert 'SERIAL_DRIVER = vendor' in rules


def test_split_sync_flags_are_not_runtime_assignments(split_rgb_kb):
    kb = split_rgb_kb.model_copy(update={
        'feature_configs': {
            'split_keyboard': {
                'SPLIT_TRANSPORT_MIRROR': 'yes',
                'SPLIT_LAYER_STATE_ENABLE': 'yes',
            },
        },
    })

    keyboard_c = generate_keyboard_c(kb)
    config = generate_config_h(kb)

    assert 'split_transport_mirror' not in keyboard_c
    assert 'split_layer_state_enable' not in keyboard_c
    assert '#define SPLIT_TRANSPORT_MIRROR' in config
    assert '#define SPLIT_LAYER_STATE_ENABLE' in config


def test_pmw_pointing_device_emits_driver_cs_define(rp2040_oled_kb):
    kb = rp2040_oled_kb.model_copy(update={
        'features': {**rp2040_oled_kb.features, 'pointing_device': True},
        'feature_configs': {
            'pointing_device': {
                'POINTING_DEVICE_DRIVER': 'pmw3360',
                'POINTING_DEVICE_CS_PIN': 'GP7',
            },
        },
    })

    config = generate_config_h(kb)

    assert '#define POINTING_DEVICE_CS_PIN GP7' in config
    assert '#define PMW33XX_CS_PIN GP7' in config


def test_imported_rp2040_audio_can_emit_pwm_driver(rp2040_oled_kb):
    kb = rp2040_oled_kb.model_copy(update={
        'features': {**rp2040_oled_kb.features, 'audio': True},
        'feature_configs': {'audio': {'AUDIO_DRIVER': 'pwm_hardware'}},
    })

    rules = generate_rules_mk(kb)
    config = generate_config_h(kb)

    assert 'AUDIO_DRIVER = pwm_hardware' in rules
    assert '#define AUDIO_PIN GP0' in config


def test_is31fl3731_on_chibios_suppresses_unused_var_warning(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'mcu': 'stm32f303',
        'features': {**minimal_avr_kb.features, 'rgb_matrix': True},
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    rules = generate_rules_mk(kb)
    assert 'CFLAGS += -Wno-error=unused-but-set-variable' in rules


def test_is31fl3731_on_avr_no_cflags_suppression(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'features': {**minimal_avr_kb.features, 'rgb_matrix': True},
        'feature_configs': {'rgb_matrix': {'RGB_MATRIX_DRIVER': 'IS31FL3731'}},
    })
    rules = generate_rules_mk(kb)
    assert 'unused-but-set-variable' not in rules


def test_rgblight_enables_effects_for_default_mode_symbols(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'features': {**minimal_avr_kb.features, 'rgblight': True},
        'feature_configs': {'rgblight': {'RGBLIGHT_DEFAULT_MODE': 'RGBLIGHT_EFFECT_BREATHING'}},
    })
    config = generate_config_h(kb)

    assert '#define RGBLIGHT_EFFECT_BREATHING' in config
    assert '#define RGBLIGHT_EFFECT_RAINBOW_SWIRL' in config
    assert '#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING' in config
    assert '#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_EFFECT_BREATHING' not in config
    assert 'RGBLIGHT_ANIMATIONS' not in config


def test_rgblight_solid_effect_alias_uses_static_light_mode(minimal_avr_kb):
    kb = minimal_avr_kb.model_copy(update={
        'features': {**minimal_avr_kb.features, 'rgblight': True},
        'feature_configs': {'rgblight': {'RGBLIGHT_DEFAULT_MODE': 'RGBLIGHT_EFFECT_SOLID'}},
    })
    config = generate_config_h(kb)

    assert '#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT' in config


# ── Real-world board tests ─────────────────────────────────────────────────────

def test_unicorne_rp2040_split_pointing_rgb_encoder(unicorne_kb):
    """boardsource/unicorne: RP2040 + split + PMW3360 + RGB matrix + encoder + audio."""
    rules = generate_rules_mk(unicorne_kb)
    config = generate_config_h(unicorne_kb)
    keymap = generate_keymap_c(unicorne_kb)
    info = json.loads(generate_info_json(unicorne_kb))

    assert 'MCU = RP2040' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'SPLIT_KEYBOARD = yes' in rules
    assert 'SPLIT_TRANSPORT = serial' in rules
    assert 'SERIAL_DRIVER = vendor' in rules
    assert 'POINTING_DEVICE_ENABLE = yes' in rules
    assert 'POINTING_DEVICE_DRIVER = pmw3360' in rules
    assert 'RGB_MATRIX_ENABLE = yes' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'AUDIO_ENABLE = yes' in rules

    assert '#define SOFT_SERIAL_PIN GP1' in config
    assert '#define POINTING_DEVICE_CS_PIN GP17' in config
    assert '#define PMW33XX_CS_PIN GP17' in config
    assert 'GP29' in config and 'GP28' in config  # row pins
    assert 'GP6' in config and 'GP11' in config   # col pins

    assert info['split']['enabled'] is True
    assert 'soft_serial_pin' in info['split']
    rgb_layout = info['rgb_matrix']['layout']
    assert len(rgb_layout) == 24  # 4 rows × 6 cols, all have led_index

    assert 'encoder_map' in keymap
    assert 'KC_VOLU' in keymap
    assert 'KC_VOLD' in keymap


def test_evo70_r2_stm32f411_backlight_rgblight_audio_encoder(evo70_r2_kb):
    """custommk/evo70_r2: STM32F411 + encoder + backlight + rgblight + audio."""
    rules = generate_rules_mk(evo70_r2_kb)
    config = generate_config_h(evo70_r2_kb)
    keymap = generate_keymap_c(evo70_r2_kb)
    info = json.loads(generate_info_json(evo70_r2_kb))

    assert 'MCU = STM32F411' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'BACKLIGHT_ENABLE = yes' in rules
    assert 'RGBLIGHT_ENABLE = yes' in rules
    assert 'AUDIO_ENABLE = yes' in rules
    assert 'BACKLIGHT_LEVELS = 5' in rules

    assert '#define AUDIO_PIN C13' in config
    assert '#define BACKLIGHT_PIN B6' in config
    assert '#define RGBLIGHT_DI_PIN B15' in config
    assert '#define RGBLIGHT_LED_COUNT 14' in config
    assert 'A4' in config and 'C12' in config  # row pins
    assert 'A3' in config and 'B11' in config  # col pins

    assert info['processor'] == 'STM32F411'
    assert info['bootloader'] == 'stm32-dfu'
    assert 'split' not in info

    assert 'encoder_map' in keymap


def test_macropad_rp2040_rgb_matrix_audio_pwm_encoder(macropad_rp2040_kb):
    """adafruit/macropad: RP2040 + encoder + RGB matrix + OLED + audio (pwm_hardware)."""
    rules = generate_rules_mk(macropad_rp2040_kb)
    config = generate_config_h(macropad_rp2040_kb)
    keymap = generate_keymap_c(macropad_rp2040_kb)
    info = json.loads(generate_info_json(macropad_rp2040_kb))

    assert 'MCU = RP2040' in rules
    assert 'RGB_MATRIX_ENABLE = yes' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'AUDIO_ENABLE = yes' in rules
    assert 'AUDIO_DRIVER = pwm_hardware' in rules

    assert '#define AUDIO_PIN GP0' in config  # default RP2040 audio pin

    assert info['processor'] == 'RP2040'
    assert info['bootloader'] == 'rp2040'
    assert 'split' not in info
    rgb_layout = info['rgb_matrix']['layout']
    assert len(rgb_layout) == 12  # 4 rows × 3 cols

    assert 'encoder_map' in keymap


def test_sofle_pico_rp2040_split_rgb_encoder(sofle_pico_kb):
    """sofle_pico: RP2040 + split + encoder + RGB matrix + OLED."""
    rules = generate_rules_mk(sofle_pico_kb)
    config = generate_config_h(sofle_pico_kb)
    keymap = generate_keymap_c(sofle_pico_kb)
    info = json.loads(generate_info_json(sofle_pico_kb))

    assert 'MCU = RP2040' in rules
    assert 'SPLIT_KEYBOARD = yes' in rules
    assert 'SPLIT_TRANSPORT = serial' in rules
    assert 'SERIAL_DRIVER = vendor' in rules
    assert 'RGB_MATRIX_ENABLE = yes' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules

    assert '#define SOFT_SERIAL_PIN GP0' in config
    assert 'GP4' in config   # row pin
    assert 'GP21' in config  # col pin

    assert info['split']['enabled'] is True
    rgb_layout = info['rgb_matrix']['layout']
    assert len(rgb_layout) == 30  # 5 rows × 6 cols

    assert 'encoder_map' in keymap


def test_preonic_rev3_stm32f303_audio_console_rgblight_encoder(preonic_rev3_kb):
    """preonic/rev3: STM32F303 + encoder + audio + console + rgblight."""
    rules = generate_rules_mk(preonic_rev3_kb)
    config = generate_config_h(preonic_rev3_kb)
    keymap = generate_keymap_c(preonic_rev3_kb)
    info = json.loads(generate_info_json(preonic_rev3_kb))

    assert 'MCU = STM32F303' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'AUDIO_ENABLE = yes' in rules
    assert 'CONSOLE_ENABLE = yes' in rules
    assert 'RGBLIGHT_ENABLE = yes' in rules

    assert '#define AUDIO_PIN C6' in config
    assert '#define RGBLIGHT_DI_PIN A1' in config
    assert '#define RGBLIGHT_LED_COUNT 2' in config
    assert 'A10' in config and 'C6' in config  # row pins
    assert 'A7' in config and 'B5' in config   # col pins

    assert info['processor'] == 'STM32F303'
    assert info['bootloader'] == 'stm32-dfu'
    assert 'split' not in info

    assert 'encoder_map' in keymap


def test_rocketboard16_stm32f103_rgblight_console_encoder(rocketboard16_kb):
    """rocketboard_16: STM32F103 + encoder + OLED + rgblight + console."""
    rules = generate_rules_mk(rocketboard16_kb)
    config = generate_config_h(rocketboard16_kb)
    keymap = generate_keymap_c(rocketboard16_kb)
    info = json.loads(generate_info_json(rocketboard16_kb))

    assert 'MCU = STM32F103' in rules
    assert 'TARGET_ARCH = ARM' in rules
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'RGBLIGHT_ENABLE = yes' in rules
    assert 'CONSOLE_ENABLE = yes' in rules
    assert 'OLED_ENABLE = yes' in rules

    assert '#define RGBLIGHT_DI_PIN B8' in config
    assert '#define RGBLIGHT_LED_COUNT 8' in config
    assert 'A1' in config and 'B12' in config  # row pins
    assert 'A2' in config and 'A7' in config   # col pins

    assert info['processor'] == 'STM32F103'
    assert info['bootloader'] == 'stm32duino'
    assert 'split' not in info

    assert 'encoder_map' in keymap


def test_zima_avr_audio_rgblight_encoder(zima_kb):
    """splitkb/zima: atmega32u4 + encoder + OLED + audio + rgblight."""
    rules = generate_rules_mk(zima_kb)
    config = generate_config_h(zima_kb)
    keymap = generate_keymap_c(zima_kb)
    info = json.loads(generate_info_json(zima_kb))

    assert 'MCU = atmega32u4' in rules
    assert 'F_CPU = 16000000' in rules
    assert 'TARGET_ARCH = ARM' not in rules  # AVR
    assert 'ENCODER_MAP_ENABLE = yes' in rules
    assert 'AUDIO_ENABLE = yes' in rules
    assert 'RGBLIGHT_ENABLE = yes' in rules
    assert 'OLED_ENABLE = yes' in rules

    assert '#define AUDIO_PIN C5' in config
    assert '#define RGBLIGHT_DI_PIN B3' in config
    assert '#define RGBLIGHT_LED_COUNT 6' in config
    assert '#define MATRIX_ROW_PINS { D4, C6 }' in config
    assert '#define MATRIX_COL_PINS { D7, E6, B4, B5, B6, D6 }' in config

    assert info['processor'] == 'atmega32u4'
    assert info['bootloader'] == 'atmel-dfu'
    assert 'split' not in info

    assert 'encoder_map' in keymap


def test_mcp_expander_pins_emit_custom_matrix(minimal_avr_kb):
    """MCP_A0-style pins must not appear in matrix_pins.rows/cols (QMK schema rejects them).
    keyboard.json should signal custom matrix, and config.h must not define MATRIX_COL/ROW_PINS."""
    config = minimal_avr_kb.model_copy(update={
        'row_pins': [MatrixPin(row=i, pin=p) for i, p in enumerate(['F7', 'F6', 'F5'])],
        'col_pins': [ColPin(col=i, pin=p) for i, p in enumerate(['MCP_A0', 'MCP_A1', 'MCP_A2', 'C6', 'D3', 'B0'])],
    })
    info = json.loads(generate_info_json(config))
    assert info.get('matrix_pins') == {'custom': True}, \
        'Non-GPIO pins must yield matrix_pins.custom=true, not a pin list'

    cfg = generate_config_h(config)
    assert 'MATRIX_ROW_PINS' not in cfg or cfg.count('MATRIX_ROW_PINS') == cfg.count('/* #define MATRIX_ROW_PINS'), \
        'MATRIX_ROW_PINS must be commented out when any pin is a C-macro alias'
    assert 'MATRIX_COL_PINS' not in cfg or cfg.count('MATRIX_COL_PINS') == cfg.count('/* #define MATRIX_COL_PINS'), \
        'MATRIX_COL_PINS must be commented out when any pin is a C-macro alias'
    assert 'MCP_A0' not in cfg, 'MCP_A0 must not appear in config.h'
