from __future__ import annotations

from models import KeyboardConfig
from codegen._matrix import matrix_rows, matrix_cols
from codegen._mcu import MCU_BOOTLOADER


def generate_config_h(config: KeyboardConfig) -> str:
    rows = matrix_rows(config)
    cols = matrix_cols(config)
    rgb_enabled = config.features.get('rgb_matrix', False)
    rgblight_enabled = config.features.get('rgblight', False)
    split_enabled = config.features.get('split_keyboard', False)
    encoder_enabled = config.features.get('encoder', False)
    oled_enabled = config.features.get('oled', False)
    audio_enabled = config.features.get('audio', False)

    lines: list[str] = [
        '#pragma once',
        '',
        '/* Generated by QMK Nexus — do not edit manually */',
        '',
        f'#define MANUFACTURER "{config.manufacturer or "Unknown"}"',
        f'#define PRODUCT "{config.name}"',
        f'#define VENDOR_ID  {config.usb_vid}',
        f'#define PRODUCT_ID {config.usb_pid}',
        '#define DEVICE_VER 0x0001',
        '',
        f'#define MATRIX_ROWS {rows}',
        f'#define MATRIX_COLS {cols}',
        '',
    ]

    if config.row_pins:
        pin_list = ', '.join(p.pin for p in sorted(config.row_pins, key=lambda p: p.row))
        lines.append(f'#define MATRIX_ROW_PINS {{ {pin_list} }}')
    else:
        lines.append('/* #define MATRIX_ROW_PINS { } */')

    if config.col_pins:
        pin_list = ', '.join(p.pin for p in sorted(config.col_pins, key=lambda p: p.col))
        lines.append(f'#define MATRIX_COL_PINS {{ {pin_list} }}')
    else:
        lines.append('/* #define MATRIX_COL_PINS { } */')

    lines += ['', '#define DIODE_DIRECTION COL2ROW', '', '#define DEBOUNCE 5', '']

    if rgb_enabled:
        led_count = len([k for k in config.keys if k.led_index is not None])
        if led_count == 0:
            led_count = len([k for k in config.keys if k.row is not None])
        lines += [
            f'#define RGB_MATRIX_LED_COUNT {led_count}',
            '#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200',
            '#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING',
            '#define RGB_MATRIX_DEFAULT_HUE 0',
            '#define RGB_MATRIX_DEFAULT_SAT 255',
            '#define RGB_MATRIX_DEFAULT_VAL 128',
            '#define RGB_MATRIX_DEFAULT_SPD 127',
            '#define RGB_MATRIX_TIMEOUT 0',
            '#define RGB_MATRIX_SLEEP',
            '',
        ]

    if rgblight_enabled:
        lines += [
            '#define RGBLIGHT_LED_COUNT 12',
            '#define RGBLIGHT_LIMIT_VAL 200',
            '#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING',
            '',
        ]

    if split_enabled:
        serial_pin = config.soft_serial_pin or 'D0'
        lines += [
            f'#define SOFT_SERIAL_PIN {serial_pin}',
            '#define SPLIT_USB_DETECT',
            '#define SPLIT_TRANSPORT_MIRROR',
            '#define SPLIT_LAYER_STATE_ENABLE',
            '#define SPLIT_LED_STATE_ENABLE',
            '#define SPLIT_MODS_ENABLE',
        ]
        if rgb_enabled:
            lines.append('#define SPLIT_RGB_MATRIX_ENABLE')
        lines.append('')

    if encoder_enabled:
        lines += ['#define ENCODER_RESOLUTION 4', '']

    if oled_enabled:
        lines += ['#define OLED_BRIGHTNESS 128', '#define OLED_TIMEOUT 60000', '']

    if audio_enabled:
        lines += ['/* #define AUDIO_PIN C6 */', '']

    lines += [f'#define BOOTLOADER {MCU_BOOTLOADER.get(config.mcu.lower(), "atmel-dfu")}', '']

    return '\n'.join(lines)
