from __future__ import annotations

from models import KeyboardConfig
from codegen._matrix import matrix_rows, matrix_cols, resolve_rgb_led_count, pins_json_safe
from codegen._mcu import MCU_BOOTLOADER


def _c_string(text: str) -> str:
    return text.replace('\\', '\\\\').replace('"', '\\"').replace('\r', ' ').replace('\n', ' ')


_RGBLIGHT_EFFECT_DEFINES = (
    '#define RGBLIGHT_EFFECT_BREATHING',
    '#define RGBLIGHT_EFFECT_RAINBOW_MOOD',
    '#define RGBLIGHT_EFFECT_RAINBOW_SWIRL',
    '#define RGBLIGHT_EFFECT_SNAKE',
    '#define RGBLIGHT_EFFECT_KNIGHT',
    '#define RGBLIGHT_EFFECT_CHRISTMAS',
    '#define RGBLIGHT_EFFECT_STATIC_GRADIENT',
    '#define RGBLIGHT_EFFECT_RGB_TEST',
    '#define RGBLIGHT_EFFECT_ALTERNATING',
    '#define RGBLIGHT_EFFECT_TWINKLE',
)


def _rgblight_default_mode(value: str) -> str:
    """QMK enables effects with RGBLIGHT_EFFECT_* but stores modes as RGBLIGHT_MODE_*."""
    if value == 'RGBLIGHT_EFFECT_SOLID':
        return 'RGBLIGHT_MODE_STATIC_LIGHT'
    if value.startswith('RGBLIGHT_EFFECT_'):
        return 'RGBLIGHT_MODE_' + value.removeprefix('RGBLIGHT_EFFECT_')
    return value


def _default_pin_for_mcu(config: KeyboardConfig, avr_pin: str, rp2040_pin: str) -> str:
    mcu = (config.mcu or '').lower()
    return rp2040_pin if mcu == 'rp2040' else avr_pin


def _default_or_mcu_pin(config: KeyboardConfig, value: str | None, avr_pin: str, rp2040_pin: str) -> str:
    mcu = (config.mcu or '').lower()
    if not value or (mcu == 'rp2040' and not value.startswith('GP')):
        return _default_pin_for_mcu(config, avr_pin, rp2040_pin)
    return value


def generate_config_h(config: KeyboardConfig) -> str:
    rows = matrix_rows(config)
    cols = matrix_cols(config)
    fc = config.feature_configs or {}
    features = config.features or {}

    lines: list[str] = [
        '#pragma once',
        '',
        '/* Generated by QMK Nexus — do not edit manually */',
        '',
        f'#define MANUFACTURER "{_c_string(config.manufacturer or "Unknown")}"',
        f'#define PRODUCT "{_c_string(config.name)}"',
        f'#define VENDOR_ID  {config.usb_vid}',
        f'#define PRODUCT_ID {config.usb_pid}',
        '#define DEVICE_VER 0x0001',
        '',
        f'#define MATRIX_ROWS {rows}',
        f'#define MATRIX_COLS {cols}',
        '',
    ]

    all_pins = [p.pin for p in config.row_pins + config.col_pins]
    _gpio_pins = pins_json_safe(all_pins)

    if config.direct_pins:
        lines.append('/* MATRIX_ROW_PINS omitted: keyboard.json uses matrix_pins.direct */')
    elif config.row_pins and _gpio_pins:
        sorted_row_pins = sorted(
            (p for p in config.row_pins if p.pin.strip()),
            key=lambda p: p.row,
        )
        if features.get('split_keyboard') and len(sorted_row_pins) > rows // 2:
            sorted_row_pins = sorted_row_pins[:rows // 2]
        if sorted_row_pins:
            pin_list = ', '.join(p.pin for p in sorted_row_pins)
            lines.append(f'#define MATRIX_ROW_PINS {{ {pin_list} }}')
    else:
        lines.append('/* #define MATRIX_ROW_PINS { } */')

    if config.direct_pins:
        lines.append('/* MATRIX_COL_PINS omitted: keyboard.json uses matrix_pins.direct */')
    elif config.col_pins and _gpio_pins:
        pin_list = ', '.join(p.pin for p in sorted(config.col_pins, key=lambda p: p.col))
        lines.append(f'#define MATRIX_COL_PINS {{ {pin_list} }}')
    else:
        lines.append('/* #define MATRIX_COL_PINS { } */')

    lines += ['', '#define DIODE_DIRECTION COL2ROW', '', '#define DEBOUNCE 5', '']

    ws2812_pin_defined = False

    if features.get('rgb_matrix'):
        rgb = fc.get('rgb_matrix', {})
        led_count = resolve_rgb_led_count(config)
        driver = rgb.get('RGB_MATRIX_DRIVER', 'WS2812')
        max_bright = rgb.get('RGB_MATRIX_MAXIMUM_BRIGHTNESS', '200')
        default_mode = rgb.get('RGB_MATRIX_DEFAULT_MODE', 'RGB_MATRIX_SOLID_COLOR')
        sleep = rgb.get('RGB_MATRIX_SLEEP', 'yes')
        lines += [
            f'#define RGB_MATRIX_LED_COUNT {led_count}',
            f'#define RGB_MATRIX_MAXIMUM_BRIGHTNESS {max_bright}',
            f'#define RGB_MATRIX_DEFAULT_MODE {default_mode}',
            '#define RGB_MATRIX_DEFAULT_HUE 0',
            '#define RGB_MATRIX_DEFAULT_SAT 255',
            '#define RGB_MATRIX_DEFAULT_VAL 128',
            '#define RGB_MATRIX_DEFAULT_SPD 127',
            '#define RGB_MATRIX_TIMEOUT 0',
        ]
        if sleep == 'yes':
            lines.append('#define RGB_MATRIX_SLEEP')
        if driver in ('IS31FL3731', 'IS31FL3733', 'IS31FL3735', 'IS31FL3736',
                      'IS31FL3737', 'IS31FL3738', 'IS31FL3741', 'IS31FL3742',
                      'IS31FL3743', 'IS31FL3744', 'IS31FL3745', 'IS31FL3746'):
            sda = rgb.get('RGB_MATRIX_I2C_SDA', 'D2')
            scl = rgb.get('RGB_MATRIX_I2C_SCL', 'D1')
            lines += [f'#define RGB_MATRIX_I2C_SDA {sda}', f'#define RGB_MATRIX_I2C_SCL {scl}']
            if driver == 'IS31FL3731':
                is_split = bool(features.get('split_keyboard'))
                driver_count = rgb.get('IS31FL3731_DRIVER_COUNT', '2' if is_split else '1')
                addr1 = rgb.get('IS31FL3731_I2C_ADDRESS_1', 'IS31FL3731_I2C_ADDRESS_GND')
                lines += [
                    f'#define IS31FL3731_DRIVER_COUNT {driver_count}',
                    f'#define IS31FL3731_I2C_ADDRESS_1 {addr1}',
                ]
                try:
                    cnt = int(driver_count)
                except ValueError:
                    cnt = 1
                if cnt >= 2:
                    addr2 = rgb.get('IS31FL3731_I2C_ADDRESS_2', 'IS31FL3731_I2C_ADDRESS_GND')
                    lines.append(f'#define IS31FL3731_I2C_ADDRESS_2 {addr2}')
                if config.mcu.lower() == 'mk20dx256':
                    lines += [
                        '#define I2C1_SCL_PAL_MODE PAL_MODE_OUTPUT_OPENDRAIN',
                        '#define I2C1_SDA_PAL_MODE PAL_MODE_OUTPUT_OPENDRAIN',
                    ]
        elif driver == 'WS2812':
            pin = rgb.get('RGB_MATRIX_PIN', 'D3')
            lines.append(f'#define WS2812_DI_PIN {pin}')
            ws2812_pin_defined = True
        lines.append('')

    if features.get('rgblight'):
        rgl = fc.get('rgblight', {})
        pin = rgl.get('RGBLIGHT_DI_PIN', rgl.get('RGBLIGHT_PIN', 'D3'))
        count = rgl.get('RGBLIGHT_LED_COUNT', '12')
        limit = rgl.get('RGBLIGHT_LIMIT_VAL', '200')
        mode = _rgblight_default_mode(rgl.get('RGBLIGHT_DEFAULT_MODE', 'RGBLIGHT_MODE_BREATHING'))
        effect_defines = _RGBLIGHT_EFFECT_DEFINES
        if (config.mcu or '').lower().startswith('atmega') and features.get('audio') and features.get('oled'):
            effect_defines = ('#define RGBLIGHT_EFFECT_BREATHING',)
        rgl_lines = [
            *effect_defines,
            f'#define RGBLIGHT_DI_PIN {pin}',
            f'#define RGBLIGHT_LED_COUNT {count}',
            f'#define RGBLIGHT_LIMIT_VAL {limit}',
            f'#define RGBLIGHT_DEFAULT_MODE {mode}',
        ]
        if not ws2812_pin_defined:
            rgl_lines.insert(1, f'#define WS2812_DI_PIN {pin}')
            ws2812_pin_defined = True
        lines += rgl_lines + ['']

    if features.get('backlight'):
        bl = fc.get('backlight', {})
        pin = bl.get('BACKLIGHT_PIN', 'B7')
        lines += [f'#define BACKLIGHT_PIN {pin}', '']

    if features.get('split_keyboard'):
        sp = fc.get('split_keyboard', {})
        transport = sp.get('SPLIT_TRANSPORT', 'serial')
        serial_pin = _default_or_mcu_pin(config, sp.get('SOFT_SERIAL_PIN') or config.soft_serial_pin, 'D2', 'GP0')
        lines += [f'#define SOFT_SERIAL_PIN {serial_pin}']
        if transport == 'i2c':
            sda = sp.get('SPLIT_I2C_SDA', 'D2')
            scl = sp.get('SPLIT_I2C_SCL', 'D1')
            lines += [f'#define SPLIT_I2C_SDA {sda}', f'#define SPLIT_I2C_SCL {scl}']
        for define in ('SPLIT_USB_DETECT', 'SPLIT_TRANSPORT_MIRROR',
                       'SPLIT_LAYER_STATE_ENABLE', 'SPLIT_LED_STATE_ENABLE', 'SPLIT_MODS_ENABLE'):
            if sp.get(define, 'yes') == 'yes':
                lines.append(f'#define {define}')
        if features.get('rgb_matrix') and sp.get('SPLIT_RGB_MATRIX_ENABLE', 'no') == 'yes':
            lines.append('#define SPLIT_RGB_MATRIX_ENABLE')
        lines.append('')

    if features.get('encoder'):
        enc = fc.get('encoder', {})
        count = enc.get('ENCODER_COUNT', '1')
        lines += [
            f'#define NUM_ENCODERS {count}',
            # ENCODER_RESOLUTION is a make variable — set in rules.mk, not here
        ]
        for i in range(int(count)):
            pad_a = enc.get(f'ENCODER_PAD_A_{i}', 'B6')
            pad_b = enc.get(f'ENCODER_PAD_B_{i}', 'B2')
            lines += [f'#define ENCODER_PIN_A_{i} {pad_a}', f'#define ENCODER_PIN_B_{i} {pad_b}']
        lines.append('')

    if features.get('oled'):
        oled = fc.get('oled', {})
        brightness = oled.get('OLED_BRIGHTNESS', '128')
        timeout = oled.get('OLED_TIMEOUT', '60000')
        lines += [
            f'#define OLED_BRIGHTNESS {brightness}',
            f'#define OLED_TIMEOUT {timeout}',
            '',
        ]

    if features.get('audio'):
        aud = fc.get('audio', {})
        pin = aud.get('AUDIO_PIN', _default_pin_for_mcu(config, 'C6', 'GP0'))
        lines += [f'#define AUDIO_PIN {pin}', '']

    if features.get('pointing_device'):
        pd = fc.get('pointing_device', {})
        driver = pd.get('POINTING_DEVICE_DRIVER', 'pmw3360')
        cs = pd.get('POINTING_DEVICE_CS_PIN')
        motion = pd.get('POINTING_DEVICE_MOTION_PIN')
        rot90 = pd.get('POINTING_DEVICE_ROTATION_90', 'no')
        inv_x = pd.get('POINTING_DEVICE_INVERT_X', 'no')
        inv_y = pd.get('POINTING_DEVICE_INVERT_Y', 'no')
        if driver in ('pmw3360', 'pmw3389') and not cs:
            cs = _default_pin_for_mcu(config, 'B0', 'GP1')
        if cs:
            lines.append(f'#define POINTING_DEVICE_CS_PIN {cs}')
            if driver in ('pmw3360', 'pmw3389'):
                lines.append(f'#define PMW33XX_CS_PIN {cs}')
            elif driver == 'adns9800':
                lines.append(f'#define ADNS9800_CS_PIN {cs}')
            elif driver == 'cirque_pinnacle_spi':
                lines.append(f'#define CIRQUE_PINNACLE_SPI_CS_PIN {cs}')
        if motion:
            lines.append(f'#define POINTING_DEVICE_MOTION_PIN {motion}')
        if rot90 == 'yes':
            lines.append('#define POINTING_DEVICE_ROTATION_90')
        if inv_x == 'yes':
            lines.append('#define POINTING_DEVICE_INVERT_X')
        if inv_y == 'yes':
            lines.append('#define POINTING_DEVICE_INVERT_Y')
        lines.append('')

    if features.get('bootmagic'):
        bm = fc.get('bootmagic', {})
        row = bm.get('BOOTMAGIC_LITE_ROW', '0')
        col = bm.get('BOOTMAGIC_LITE_COLUMN', '0')
        lines += [
            f'#define BOOTMAGIC_LITE_ROW {row}',
            f'#define BOOTMAGIC_LITE_COLUMN {col}',
            '',
        ]

    bootloader = MCU_BOOTLOADER.get(config.mcu.lower(), 'atmel-dfu')
    lines += [f'#define BOOTLOADER {bootloader}', '']

    return '\n'.join(lines)
