from __future__ import annotations

from models import KeyboardConfig
from codegen._mcu import MCU_ARCH, MCU_BOOTLOADER, MCU_RGB_DRIVER

_FEATURE_MAP: dict[str, str] = {
    'rgb_matrix': 'RGB_MATRIX_ENABLE',
    'rgblight': 'RGBLIGHT_ENABLE',
    'backlight': 'BACKLIGHT_ENABLE',
    'encoder': 'ENCODER_ENABLE',
    'oled': 'OLED_ENABLE',
    'split_keyboard': 'SPLIT_KEYBOARD',
    'nkro': 'NKRO_ENABLE',
    'bootmagic': 'BOOTMAGIC_ENABLE',
    'mousekey': 'MOUSEKEY_ENABLE',
    'extrakey': 'EXTRAKEY_ENABLE',
    'console': 'CONSOLE_ENABLE',
    'command': 'COMMAND_ENABLE',
    'tap_dance': 'TAP_DANCE_ENABLE',
    'combo': 'COMBO_ENABLE',
    'key_lock': 'KEY_LOCK_ENABLE',
    'audio': 'AUDIO_ENABLE',
}


def generate_rules_mk(config: KeyboardConfig) -> str:
    mcu = config.mcu.lower()
    arch, f_cpu = MCU_ARCH.get(mcu, ('avr', '16000000'))

    lines: list[str] = [
        '# Generated by QMK Nexus — do not edit manually',
        '',
        f'MCU = {mcu}',
        f'ARCH = {arch}',
        f'F_CPU = {f_cpu}',
        '',
    ]

    if arch == 'avr':
        lines.append('F_USB = $(F_CPU)')
        lines.append('OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT')
        lines.append('')

    if arch == 'chibios':
        lines.append('PLATFORM_KEY = chibios')
        if mcu == 'rp2040':
            lines.append('MCU_FAMILY = RP2040')
        lines.append('')

    rgb_enabled = config.features.get('rgb_matrix', False)
    lines.append('# Feature flags')
    for feature_id, rules_key in _FEATURE_MAP.items():
        enabled = config.features.get(feature_id, False)
        lines.append(f'{rules_key} = {"yes" if enabled else "no"}')
    lines.append('')

    if rgb_enabled:
        driver = MCU_RGB_DRIVER.get(mcu, 'ws2812')
        lines.append(f'RGB_MATRIX_DRIVER = {driver}')
        lines.append('')

    lines.append('# Bootloader')
    lines.append(f'BOOTLOADER = {MCU_BOOTLOADER.get(mcu, "atmel-dfu")}')
    lines.append('')
    lines.append('# Default LTO for size')
    lines.append('LTO_ENABLE = yes')
    lines.append('')

    return '\n'.join(lines)
