import { KeyboardLayoutMeta, FeatureConfig } from './types';

export const featureDefinitions: FeatureConfig[] = [
  {
    id: 'extrakeys',
    name: 'Extra Keys',
    description: 'Media and system control keys (volume, play, brightness).',
    usagePercent: 67,
    enabled: false,
    lockedOn: false,
  },
  {
    id: 'bootmagic',
    name: 'Boot Magic',
    description: 'Hold a key at power-on to enter bootloader or change settings.',
    usagePercent: 55,
    enabled: false,
    lockedOn: false,
  },
  {
    id: 'mousekeys',
    name: 'Mouse Keys',
    description: 'Control the mouse cursor and buttons from keyboard keys.',
    usagePercent: 52,
    enabled: false,
    lockedOn: false,
  },
  {
    id: 'nkro',
    name: 'N-Key Rollover',
    description: 'Report all simultaneous keypresses without USB protocol limits.',
    usagePercent: 43,
    enabled: false,
    lockedOn: false,
    warnings: [
      {
        type: 'hardware',
        message: 'N-Key Rollover requires a diode per key (COL2ROW or ROW2COL wiring). A matrix without diodes will ghost and cannot benefit from NKRO.',
      },
    ],
  },
  {
    id: 'rgblight',
    name: 'RGB Light (Underglow)',
    description: 'WS2812-style per-LED underglow strip lighting with animations.',
    usagePercent: 24,
    enabled: false,
    lockedOn: false,
    inputs: [
      {
        id: 'rgblight_pin',
        label: 'RGB Data Pin (DI)',
        type: 'pin',
        placeholder: 'e.g. D3, B6',
        required: true,
        layoutKey: 'rgbLightPin',
        helpText: 'The GPIO pin connected to the DIN of the first WS2812 LED.',
      },
      {
        id: 'rgblight_led_count',
        label: 'Number of LEDs',
        type: 'number',
        placeholder: 'e.g. 12',
        required: true,
        derivedFromLayout: true,
        layoutKey: 'rgbLedCount',
        validation: { min: 1, max: 256 },
        helpText: 'Total number of WS2812 LEDs in the underglow strip.',
      },
    ],
  },
  {
    id: 'rgb_matrix',
    name: 'RGB Matrix',
    description: 'Per-key RGB LED control via a matrix driver (IS31FL3xxx, WS2812).',
    usagePercent: 11,
    enabled: false,
    lockedOn: false,
    inputs: [
      {
        id: 'rgb_matrix_driver',
        label: 'RGB Matrix Driver',
        type: 'select',
        required: true,
        layoutKey: 'rgbMatrixDriver',
        options: [
          { value: 'ws2812', label: 'WS2812' },
          { value: 'is31fl3731', label: 'IS31FL3731' },
          { value: 'is31fl3733', label: 'IS31FL3733' },
          { value: 'is31fl3737', label: 'IS31FL3737' },
          { value: 'is31fl3741', label: 'IS31FL3741' },
          { value: 'aw20216s', label: 'AW20216S' },
        ],
        helpText: 'Select the LED driver IC used on your PCB.',
      },
      {
        id: 'rgb_matrix_pin',
        label: 'RGB Data Pin (DI)',
        type: 'pin',
        placeholder: 'e.g. D3, B6',
        required: true,
        layoutKey: 'rgbMatrixPin',
        helpText: 'The GPIO pin connected to the DIN of the first WS2812 LED.',
        conditionalOn: { field: 'rgb_matrix_driver', values: ['ws2812'] },
      },
      {
        id: 'rgb_matrix_sda_pin',
        label: 'I2C SDA Pin',
        type: 'pin',
        placeholder: 'e.g. D1',
        required: true,
        layoutKey: 'rgbMatrixSda',
        helpText: 'The GPIO pin used for I2C data (SDA).',
        conditionalOn: { field: 'rgb_matrix_driver', values: ['is31fl3731', 'is31fl3733', 'is31fl3737', 'is31fl3741', 'aw20216s'] },
      },
      {
        id: 'rgb_matrix_scl_pin',
        label: 'I2C SCL Pin',
        type: 'pin',
        placeholder: 'e.g. D0',
        required: true,
        layoutKey: 'rgbMatrixScl',
        helpText: 'The GPIO pin used for I2C clock (SCL).',
        conditionalOn: { field: 'rgb_matrix_driver', values: ['is31fl3731', 'is31fl3733', 'is31fl3737', 'is31fl3741', 'aw20216s'] },
      },
      {
        id: 'rgb_matrix_led_count',
        label: 'Number of LEDs',
        type: 'number',
        placeholder: 'e.g. 64',
        required: true,
        derivedFromLayout: true,
        layoutKey: 'rgbMatrixLedCount',
        validation: { min: 1, max: 256 },
        helpText: 'Total number of RGB LEDs in the matrix.',
      },
    ],
  },
  {
    id: 'encoder',
    name: 'Encoder',
    description: 'Rotary encoder support with per-layer actions.',
    usagePercent: 13,
    enabled: false,
    lockedOn: false,
    inputs: [
      {
        id: 'encoder_count',
        label: 'Number of Encoders',
        type: 'number',
        placeholder: 'e.g. 1',
        required: true,
        derivedFromLayout: true,
        layoutKey: 'encoderCount',
        validation: { min: 1, max: 8 },
        helpText: 'How many rotary encoders are wired to the MCU.',
      },
      {
        id: 'encoder_pad_a',
        label: 'Pad A Pin(s)',
        type: 'text',
        placeholder: 'e.g. B2 or B2, F4',
        required: true,
        layoutKey: 'encoderPadA',
        helpText: 'Comma-separated list of GPIO pins for encoder pad A (one per encoder).',
      },
      {
        id: 'encoder_pad_b',
        label: 'Pad B Pin(s)',
        type: 'text',
        placeholder: 'e.g. B3 or B3, F5',
        required: true,
        layoutKey: 'encoderPadB',
        helpText: 'Comma-separated list of GPIO pins for encoder pad B (one per encoder).',
      },
      {
        id: 'encoder_resolution',
        label: 'Encoder Resolution',
        type: 'number',
        placeholder: '4',
        required: false,
        defaultValue: '4',
        validation: { min: 1, max: 8 },
        helpText: 'Number of pulses per detent. Most encoders use 4.',
      },
    ],
  },
  {
    id: 'split',
    name: 'Split Keyboard',
    description: 'Bidirectional split keyboard communication over TRRS/USART.',
    usagePercent: 9,
    enabled: false,
    lockedOn: false,
    warnings: [
      {
        type: 'caution',
        message: 'Both halves must be running the same firmware. Ensure your TRRS cable is wired correctly—miswiring can damage your MCU.',
      },
    ],
    inputs: [
      {
        id: 'split_transport',
        label: 'Split Transport',
        type: 'select',
        required: true,
        layoutKey: 'splitTransport',
        options: [
          { value: 'serial', label: 'Soft Serial (single-wire, TRRS)' },
          { value: 'i2c', label: 'I2C' },
        ],
        helpText: 'Communication protocol between halves.',
      },
      {
        id: 'soft_serial_pin',
        label: 'Soft Serial Pin',
        type: 'pin',
        placeholder: 'e.g. D2',
        required: true,
        layoutKey: 'softSerialPin',
        helpText: 'The GPIO pin used for single-wire serial communication (typically D2 on Pro Micro).',
        conditionalOn: { field: 'split_transport', values: ['serial'] },
      },
      {
        id: 'split_i2c_sda',
        label: 'I2C SDA Pin',
        type: 'pin',
        placeholder: 'e.g. D1',
        required: true,
        layoutKey: 'splitI2cSda',
        helpText: 'The GPIO pin used for I2C data.',
        conditionalOn: { field: 'split_transport', values: ['i2c'] },
      },
      {
        id: 'split_i2c_scl',
        label: 'I2C SCL Pin',
        type: 'pin',
        placeholder: 'e.g. D0',
        required: true,
        layoutKey: 'splitI2cScl',
        helpText: 'The GPIO pin used for I2C clock.',
        conditionalOn: { field: 'split_transport', values: ['i2c'] },
      },
      {
        id: 'split_master',
        label: 'Master Side',
        type: 'select',
        required: true,
        defaultValue: 'left',
        layoutKey: 'splitMaster',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
          { value: 'eeprom', label: 'EEPROM (set per half)' },
          { value: 'usb', label: 'USB detection (auto)' },
        ],
        helpText: 'Which half is the master. USB detection checks which side is plugged in.',
      },
    ],
  },
  {
    id: 'oled',
    name: 'OLED Display',
    description: 'OLED screen support (typically SSD1306 over I2C).',
    usagePercent: 5,
    enabled: false,
    lockedOn: false,
    inputs: [
      {
        id: 'oled_count',
        label: 'Number of OLED Displays',
        type: 'number',
        placeholder: '1',
        required: true,
        derivedFromLayout: true,
        layoutKey: 'oledCount',
        validation: { min: 1, max: 4 },
        helpText: 'Number of OLED displays. Split keyboards may have one per half.',
      },
    ],
  },
  {
    id: 'backlight',
    name: 'Backlight',
    description: 'Simple single-color PWM backlight for switches.',
    usagePercent: 10,
    enabled: false,
    lockedOn: false,
    inputs: [
      {
        id: 'backlight_pin',
        label: 'Backlight Pin',
        type: 'pin',
        placeholder: 'e.g. B7',
        required: true,
        layoutKey: 'backlightPin',
        helpText: 'The GPIO pin (must support PWM) connected to the backlight LEDs.',
      },
      {
        id: 'backlight_levels',
        label: 'Brightness Levels',
        type: 'number',
        placeholder: '3',
        required: false,
        defaultValue: '3',
        validation: { min: 1, max: 15 },
        helpText: 'Number of brightness steps the user can cycle through.',
      },
    ],
  },
  {
    id: 'console',
    name: 'Console',
    description: 'HID console for debug output via hid_listen.',
    usagePercent: 13,
    enabled: false,
    lockedOn: false,
    warnings: [
      {
        type: 'info',
        message: 'Enabling the console adds ~1.5 KB to firmware size and introduces a small amount of input latency. Recommended for development only.',
      },
    ],
  },
  {
    id: 'tap_dance',
    name: 'Tap Dance',
    description: 'Different actions on single tap, double tap, or hold.',
    usagePercent: 1,
    enabled: false,
    lockedOn: false,
  },
  {
    id: 'combo',
    name: 'Combo Keys',
    description: 'Trigger actions when multiple keys are pressed simultaneously.',
    usagePercent: 1,
    enabled: false,
    lockedOn: false,
  },
  {
    id: 'audio',
    name: 'Audio',
    description: 'Piezo buzzer or PWM speaker with musical notes.',
    usagePercent: 2,
    enabled: false,
    lockedOn: false,
    warnings: [
      {
        type: 'hardware',
        message: 'Audio requires a piezo buzzer or speaker wired to the specified pin. Without the hardware component, this feature has enough effect.',
      },
    ],
    inputs: [
      {
        id: 'audio_pin',
        label: 'Audio Pin',
        type: 'pin',
        placeholder: 'e.g. C6',
        required: true,
        layoutKey: 'audioPin',
        helpText: 'The GPIO pin connected to the piezo buzzer or speaker.',
      },
    ],
  },
];
