"""Curated feature module definitions for the qmk-nexus editor."""

from dataclasses import dataclass, field


@dataclass
class FeatureModule:
    id: str
    name: str
    description: str
    rules_mk_key: str
    required_config: list[str] = field(default_factory=list)
    optional_config: list[str] = field(default_factory=list)
    incompatible_with: list[str] = field(default_factory=list)
    qmk_prevalence: float = 0.0


MODULES: list[FeatureModule] = [
    FeatureModule(
        id="rgblight",
        name="RGB Light (Underglow)",
        description="WS2812-style per-LED underglow/strip lighting with layered animations.",
        rules_mk_key="RGBLIGHT_ENABLE",
        required_config=[],
        optional_config=[
            "RGBLIGHT_LED_COUNT",
            "RGBLIGHT_LIMIT_VAL",
            "RGBLIGHT_DEFAULT_MODE",
            "RGBLIGHT_DEFAULT_HUE",
            "RGBLIGHT_DEFAULT_SAT",
            "RGBLIGHT_DEFAULT_VAL",
            "RGBLIGHT_DEFAULT_SPD",
            "RGBLIGHT_SLEEP",
            "RGBLIGHT_ANIMATIONS",
        ],
        incompatible_with=["rgb_matrix"],
        qmk_prevalence=0.2437,
    ),
    FeatureModule(
        id="rgb_matrix",
        name="RGB Matrix",
        description="Per-key RGB LED control via a matrix driver (IS31FL3xxx, WS2812, etc.).",
        rules_mk_key="RGB_MATRIX_ENABLE",
        required_config=["RGB_MATRIX_LED_COUNT"],
        optional_config=[
            "RGB_MATRIX_MAXIMUM_BRIGHTNESS",
            "RGB_MATRIX_DEFAULT_MODE",
            "RGB_MATRIX_DEFAULT_HUE",
            "RGB_MATRIX_DEFAULT_SAT",
            "RGB_MATRIX_DEFAULT_VAL",
            "RGB_MATRIX_DEFAULT_SPD",
            "RGB_MATRIX_TIMEOUT",
            "RGB_MATRIX_SLEEP",
        ],
        incompatible_with=["backlight"],
        qmk_prevalence=0.1106,
    ),
    FeatureModule(
        id="backlight",
        name="Backlight",
        description="Simple single-color PWM backlight for switches or underglow.",
        rules_mk_key="BACKLIGHT_ENABLE",
        required_config=[],
        optional_config=[
            "BACKLIGHT_LEVELS",
            "BACKLIGHT_DEFAULT_LEVEL",
            "BACKLIGHT_BREATHING",
            "BACKLIGHT_BREATHING_PERIOD",
        ],
        incompatible_with=[],
        qmk_prevalence=0.1021,
    ),
    FeatureModule(
        id="encoder",
        name="Encoder",
        description="Rotary encoder support with per-layer actions.",
        rules_mk_key="ENCODER_ENABLE",
        required_config=[],
        optional_config=[
            "ENCODER_RESOLUTION",
            "ENCODER_DIRECTION_FLIP",
        ],
        incompatible_with=[],
        qmk_prevalence=0.1311,
    ),
    FeatureModule(
        id="oled",
        name="OLED Display",
        description="OLED screen support (typically SSD1306 over I2C).",
        rules_mk_key="OLED_ENABLE",
        required_config=[],
        optional_config=[
            "OLED_DISPLAY_128X64",
            "OLED_BRIGHTNESS",
            "OLED_TIMEOUT",
            "OLED_FADE_OUT",
            "OLED_SCROLL_TIMEOUT",
        ],
        incompatible_with=[],
        qmk_prevalence=0.0495,
    ),
    FeatureModule(
        id="split_keyboard",
        name="Split Keyboard",
        description="Bidirectional split keyboard communication over TRRS/USART.",
        rules_mk_key="SPLIT_KEYBOARD",
        required_config=["SOFT_SERIAL_PIN"],
        optional_config=[
            "SPLIT_USB_DETECT",
            "SPLIT_TRANSPORT_MIRROR",
            "SPLIT_LAYER_STATE_ENABLE",
            "SPLIT_LED_STATE_ENABLE",
            "SPLIT_MODS_ENABLE",
            "SPLIT_WPM_ENABLE",
            "SPLIT_OLED_ENABLE",
            "SPLIT_WATCHDOG_ENABLE",
            "MASTER_LEFT",
            "MASTER_RIGHT",
            "EE_HANDS",
        ],
        incompatible_with=[],
        qmk_prevalence=0.0931,
    ),
    FeatureModule(
        id="nkro",
        name="N-Key Rollover",
        description="Report all simultaneous keypresses without USB protocol limits.",
        rules_mk_key="NKRO_ENABLE",
        required_config=[],
        optional_config=["FORCE_NKRO"],
        incompatible_with=[],
        qmk_prevalence=0.4277,
    ),
    FeatureModule(
        id="bootmagic",
        name="Boot Magic",
        description="Hold a key at power-on to enter bootloader or change settings.",
        rules_mk_key="BOOTMAGIC_ENABLE",
        required_config=[],
        optional_config=[
            "BOOTMAGIC_LITE_ROW",
            "BOOTMAGIC_LITE_COLUMN",
        ],
        incompatible_with=[],
        qmk_prevalence=0.5536,
    ),
    FeatureModule(
        id="mousekey",
        name="Mouse Keys",
        description="Control the mouse cursor and buttons from keyboard keys.",
        rules_mk_key="MOUSEKEY_ENABLE",
        required_config=[],
        optional_config=[
            "MOUSEKEY_DELAY",
            "MOUSEKEY_INTERVAL",
            "MOUSEKEY_MAX_SPEED",
            "MOUSEKEY_TIME_TO_MAX",
            "MOUSEKEY_WHEEL_DELAY",
        ],
        incompatible_with=[],
        qmk_prevalence=0.5238,
    ),
    FeatureModule(
        id="extrakey",
        name="Extra Keys",
        description="Media and system control keys (volume, play, brightness, etc.).",
        rules_mk_key="EXTRAKEY_ENABLE",
        required_config=[],
        optional_config=[],
        incompatible_with=[],
        qmk_prevalence=0.67,
    ),
    FeatureModule(
        id="console",
        name="Console",
        description="HID console interface for debug output via hid_listen.",
        rules_mk_key="CONSOLE_ENABLE",
        required_config=[],
        optional_config=["CONSOLE_ENABLE_PRINT"],
        incompatible_with=[],
        qmk_prevalence=0.1249,
    ),
    FeatureModule(
        id="command",
        name="Command",
        description="Magic key combinations to trigger firmware commands at runtime.",
        rules_mk_key="COMMAND_ENABLE",
        required_config=[],
        optional_config=["IS_COMMAND"],
        incompatible_with=[],
        qmk_prevalence=0.1434,
    ),
    FeatureModule(
        id="tap_dance",
        name="Tap Dance",
        description="Different actions on single tap, double tap, hold, etc.",
        rules_mk_key="TAP_DANCE_ENABLE",
        required_config=[],
        optional_config=[
            "TAPPING_TERM",
            "TAPPING_TOGGLE",
        ],
        incompatible_with=[],
        qmk_prevalence=0.0072,
    ),
    FeatureModule(
        id="combo",
        name="Combo Keys",
        description="Trigger actions when multiple keys are pressed simultaneously.",
        rules_mk_key="COMBO_ENABLE",
        required_config=[],
        optional_config=[
            "COMBO_COUNT",
            "COMBO_TERM",
            "COMBO_MUST_HOLD_MODS",
            "COMBO_MUST_TAP_MODS",
        ],
        incompatible_with=[],
        qmk_prevalence=0.0115,
    ),
    FeatureModule(
        id="key_lock",
        name="Key Lock",
        description="Lock a key in its pressed state until pressed again.",
        rules_mk_key="KEY_LOCK_ENABLE",
        required_config=[],
        optional_config=[],
        incompatible_with=[],
        qmk_prevalence=0.0066,
    ),
    FeatureModule(
        id="audio",
        name="Audio",
        description="Piezo buzzer or PWM speaker support with musical notes and songs.",
        rules_mk_key="AUDIO_ENABLE",
        required_config=["AUDIO_PIN"],
        optional_config=[
            "AUDIO_CLICKY",
            "AUDIO_DEFAULT_ON",
            "AUDIO_DEFAULT_CLICKY_ON",
            "STARTUP_SONG",
            "GOODBYE_SONG",
            "DEFAULT_LAYER_SONGS",
        ],
        incompatible_with=[],
        qmk_prevalence=0.016,
    ),
]

MODULES_BY_ID: dict[str, FeatureModule] = {m.id: m for m in MODULES}
